import type { Project } from "@/lib/types";

export const projects: Project[] = [
  {
    id: "actionaid-cms",
    year: "2026",
    title: "Complaint Management System",
    client: "ActionAid Bangladesh",
    category: "Enterprise · NGO Tech",
    upscaleUrl: "https://upscalebd.com/case-studies/4",
  },
  {
    id: "healthcarex",
    year: "2026",
    title: "HealthCareX Platform",
    client: "Healthcare",
    category: "Strategy · Product",
    upscaleUrl: "https://upscalebd.com/products/healthcarex",
  },
  {
    id: "pathfinder",
    year: "2026",
    title: "Pathfinder Career Navigator",
    client: "Pathfinder · UpscaleBD",
    category: "Brand · Growth",
    upscaleUrl: "https://upscalebd.com/products/pathfinder",
  },
  // {
  //   id: "actionaid-proc",
  //   year: "2026",
  //   title: "Procurement Automation Platform",
  //   client: "ActionAid Bangladesh",
  //   category: "Enterprise SaaS",
  //   upscaleUrl: "https://upscalebd.com/products/pmx",
  // },
  // {
  //   id: "prime-bank",
  //   year: "2026",
  //   title: "Regulatory Automation Pilot",
  //   client: "Prime Bank Ltd.",
  //   category: "Banking · Automation",
  //   upscaleUrl: "https://upscalebd.com/contact",
  // },
  // {
  //   id: "coats",
  //   year: "2026",
  //   title: "L&D Transformation Programme",
  //   client: "Coats Bangladesh",
  //   category: "Consulting · L&D",
  //   upscaleUrl: "https://upscalebd.com/products/calibrax",
  // },
  {
    id: "hameem",
    year: "2026",
    title: "HR Tech Suite for 75K+ Workforce",
    client: "Ha-Meem Group",
    category: "Enterprise HRIS",
    upscaleUrl: "https://upscalebd.com/products/hrx",
  },
  // {
  //   id: "textilex",
  //   year: "2025",
  //   title: "TextileX Cross-Border Platform",
  //   client: "B2B Trade · Canada/BD",
  //   category: "Marketplace",
  //   upscaleUrl: "https://upscalebd.com/contact",
  // },
  {
    id: "bsrm-cashless",
    year: "2025",
    title: "Transforming Market Intelligence",
    client: "BSRM",
    category: "Finance · Automation",
    upscaleUrl: "https://upscalebd.com/case-studies/3",
  },
  {
    id: "talentbridge",
    year: "2025",
    title: "TalentBridge Canada",
    client: "Immigrant Talent Ecosystem",
    category: "Platform · GovTech",
    upscaleUrl: "https://upscalebd.com/contact",
  },
  {
    id: "architecting",
    year: "2025",
    title: "Architecting Agile HR Systems",
    client: "Sheba Platform Ltd.",
    category: "Corporate HRM",
    upscaleUrl: "https://upscalebd.com/case-studies/2",
  },
  {
    id: "social-impact",
    year: "2024",
    title: "Social Impact Platform",
    client: "ActionAid Bangladesh",
    category: "Community Management",
    upscaleUrl: "https://upscalebd.com/case-studies/1",
  },
];
