export interface Skill {
  name: string;
}

export interface SkillCategory {
  id: string;
  label: string;
  skills: Skill[];
}

export const skillCategories: SkillCategory[] = [
  {
    id: "industry",
    label: "Industry Knowledge",
    skills: [
      { name: "Management Consulting" },
      { name: "Business Strategy" },
      { name: "Strategic Planning for Growth" },
      { name: "Business Process Re-engineering" },
      { name: "Growth Strategies" },
      { name: "Revenue & Profit Growth" },
      { name: "Start-up Consulting" },
      { name: "Business-to-Business (B2B)" },
      { name: "Early-Stage Startups" },
      { name: "Corporate Strategy" },
      { name: "New Business Development" },
      { name: "Start-ups Management" },
      { name: "Brand Strategy" },
      { name: "Supply Chain Optimization" },
      { name: "Supply Chain Management" },
      { name: "Trade Marketing" },
      { name: "Sales and Marketing" },
      { name: "Sales Management" },
      { name: "Sales Operations" },
      { name: "Sales Processes" },
      { name: "Key Account Development" },
      { name: "Key Account Management" },
      { name: "Account Management" },
      { name: "Customer Relationship Management (CRM)" },
      { name: "Customer Engagement" },
      { name: "Customer Insight" },
      { name: "Market Research" },
      { name: "Market Analysis" },
      { name: "Market Planning" },
      { name: "Competitive Analysis" },
      { name: "Segmentation" },
      { name: "Pricing Strategy" },
      { name: "Distribution Strategies" },
      { name: "Commercial Management" },
      { name: "B2B Marketing Strategy" },
      { name: "FMCG" },
      { name: "Retail" },
      { name: "Real Estate Development" },
      { name: "Building Materials" },
      { name: "International Business" },
      { name: "International Trade" },
      { name: "Social Entrepreneurship" },
      { name: "Sustainable Development" },
    ],
  },
  {
    id: "marketing",
    label: "Marketing & Brand",
    skills: [
      { name: "Marketing Strategy" },
      { name: "Marketing Management" },
      { name: "Marketing Communications" },
      { name: "Marketing Research" },
      { name: "Integrated Marketing" },
      { name: "Digital Marketing" },
      { name: "Digital Strategy" },
      { name: "Advertising" },
      { name: "Brand Management" },
      { name: "Brand Development" },
      { name: "Brand Architecture" },
      { name: "Product Marketing" },
      { name: "Product Development" },
      { name: "Growth Hacking" },
      { name: "Marketing" },
    ],
  },
  {
    id: "analytics",
    label: "Analytics & Data",
    skills: [
      { name: "Data Analysis" },
      { name: "Analytical Skills" },
      { name: "Statistical Data Analysis" },
      { name: "Data Modeling" },
      { name: "Predictive Modeling" },
      { name: "Financial Modeling" },
      { name: "Financial Analysis" },
      { name: "Financial Statement Analysis" },
      { name: "Quantitative Research" },
      { name: "Qualitative Research" },
      { name: "Policy Analysis" },
      { name: "Economic Modeling" },
      { name: "Economic Policy" },
      { name: "Econometrics" },
      { name: "International Economics" },
      { name: "Forecasting" },
    ],
  },
  {
    id: "tools",
    label: "Tools & Technologies",
    skills: [
      { name: "Python (Programming Language)" },
      { name: "Microsoft Excel" },
      { name: "Microsoft Office" },
      { name: "IBM SPSS Statistics" },
      { name: "SPSS" },
    ],
  },
  {
    id: "management",
    label: "Management & Leadership",
    skills: [
      { name: "Leadership" },
      { name: "Management" },
      { name: "Team Management" },
      { name: "Team Building" },
      { name: "Teamwork" },
      { name: "Cross-functional Team Leadership" },
      { name: "Change Management" },
      { name: "Performance Management" },
      { name: "Project Management" },
      { name: "Project Planning" },
      { name: "Program Management" },
      { name: "Software Project Management" },
      { name: "Business Planning" },
      { name: "Business Development" },
      { name: "Strategic Planning" },
      { name: "Planning" },
      { name: "Training" },
    ],
  },
  {
    id: "interpersonal",
    label: "Interpersonal Skills",
    skills: [
      { name: "Problem Solving" },
      { name: "Negotiation" },
      { name: "Pitching Ideas" },
      { name: "Communication" },
    ],
  },
];
